-- ONE-TIME ESTUARY SNOWFLAKE BOOTSTRAP.
-- Run in Snowflake as ACCOUNTADMIN only after generating the Estuary RSA key pair.
-- Replace __PUBLIC_KEY_BODY__ with the base64 body of rsa_key.pub (no BEGIN/END lines).
-- The private key must NEVER be committed or pasted into this file.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS PET_INSURANCE_ESTUARY_ROLE;

CREATE USER IF NOT EXISTS PET_INSURANCE_ESTUARY
  TYPE = SERVICE
  DEFAULT_ROLE = PET_INSURANCE_ESTUARY_ROLE
  DEFAULT_WAREHOUSE = SNOWFLAKE_LEARNING_WH;

GRANT ROLE PET_INSURANCE_ESTUARY_ROLE TO USER PET_INSURANCE_ESTUARY;

ALTER USER PET_INSURANCE_ESTUARY
  SET QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE;

ALTER USER PET_INSURANCE_ESTUARY
  SET RSA_PUBLIC_KEY = '__PUBLIC_KEY_BODY__';

CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_LEARNING_DB.PET_INSURANCE_ESTUARY;

GRANT USAGE ON DATABASE SNOWFLAKE_LEARNING_DB
  TO ROLE PET_INSURANCE_ESTUARY_ROLE;

GRANT USAGE ON WAREHOUSE SNOWFLAKE_LEARNING_WH
  TO ROLE PET_INSURANCE_ESTUARY_ROLE;

GRANT USAGE, CREATE TABLE, CREATE STAGE
  ON SCHEMA SNOWFLAKE_LEARNING_DB.PET_INSURANCE_ESTUARY
  TO ROLE PET_INSURANCE_ESTUARY_ROLE;

DESC USER PET_INSURANCE_ESTUARY;

-- Verify RSA_PUBLIC_KEY_FP is populated before configuring Estuary.
