USE ROLE <% role %>;
USE WAREHOUSE <% warehouse %>;
USE DATABASE <% database %>;

CREATE SCHEMA IF NOT EXISTS PET_INSURANCE_GCP;

CREATE OR REPLACE FILE FORMAT PET_INSURANCE_GCP.BACKFILL_CSV
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL');

CREATE OR REPLACE STAGE PET_INSURANCE_GCP.CLAIMS_BACKFILL_STAGE
  URL = 'gcs://<% bucket %>/pet-insurance-backfill/'
  STORAGE_INTEGRATION = PET_INSURANCE_GCS_INTEGRATION
  FILE_FORMAT = PET_INSURANCE_GCP.BACKFILL_CSV;

CREATE OR REPLACE TABLE PET_INSURANCE_GCP.CLAIMS_BACKFILL (
  CLAIM_ID VARCHAR,
  POLICY_ID VARCHAR,
  PET_ID VARCHAR,
  CLAIM_TYPE VARCHAR,
  CLAIM_DATE DATE,
  CLAIM_AMOUNT NUMBER(12,2),
  APPROVED_AMOUNT NUMBER(12,2),
  CLAIM_STATUS VARCHAR,
  UPDATED_AT TIMESTAMP_TZ,
  IS_DELETED BOOLEAN
);

COPY INTO PET_INSURANCE_GCP.CLAIMS_BACKFILL
FROM @PET_INSURANCE_GCP.CLAIMS_BACKFILL_STAGE/claims_backfill.csv
FILE_FORMAT = (FORMAT_NAME = PET_INSURANCE_GCP.BACKFILL_CSV)
FORCE = TRUE;
