-- One-time Snowflake bootstrap.
-- Run as ACCOUNTADMIN in Snowsight. Safe to rerun: CREATE statements are idempotent
-- and ALTER USER refreshes the GitHub OIDC trust on an existing service user.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS PET_INSURANCE_CICD_ROLE;

CREATE WAREHOUSE IF NOT EXISTS PET_INSURANCE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS PET_INSURANCE_ANALYTICS;

GRANT USAGE, OPERATE ON WAREHOUSE PET_INSURANCE_WH TO ROLE PET_INSURANCE_CICD_ROLE;
GRANT USAGE ON DATABASE PET_INSURANCE_ANALYTICS TO ROLE PET_INSURANCE_CICD_ROLE;
GRANT CREATE SCHEMA ON DATABASE PET_INSURANCE_ANALYTICS TO ROLE PET_INSURANCE_CICD_ROLE;

CREATE USER IF NOT EXISTS PET_INSURANCE_GITHUB
  TYPE = SERVICE
  DEFAULT_ROLE = PET_INSURANCE_CICD_ROLE
  COMMENT = 'Secretless GitHub Actions service user for pet-insurance-data-platform';

ALTER USER PET_INSURANCE_GITHUB SET
  WORKLOAD_IDENTITY = (
    TYPE = OIDC
    ISSUER = 'https://token.actions.githubusercontent.com'
    SUBJECT = 'repo:NiknaxTheGreek@97730962/pet-insurance-data-platform@1383094257:ref:refs/heads/main'
  )
  DEFAULT_ROLE = PET_INSURANCE_CICD_ROLE
  COMMENT = 'Secretless GitHub Actions service user for pet-insurance-data-platform';

GRANT ROLE PET_INSURANCE_CICD_ROLE TO USER PET_INSURANCE_GITHUB;

DESCRIBE USER PET_INSURANCE_GITHUB;

SELECT CURRENT_ACCOUNT() AS account_locator,
       CURRENT_ORGANIZATION_NAME() AS organization_name,
       CURRENT_ACCOUNT_NAME() AS account_name,
       CURRENT_REGION() AS region,
       CURRENT_USER() AS bootstrap_user;
