-- One-time account bootstrap for GitHub Actions OIDC.
-- Run this entire file once as ACCOUNTADMIN. It is safe to rerun.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS PET_INSURANCE_CICD_ROLE
  COMMENT = 'Least-privilege CI/CD role for pet-insurance-data-platform';

CREATE WAREHOUSE IF NOT EXISTS PET_INSURANCE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS PET_INSURANCE_ANALYTICS;

GRANT USAGE, OPERATE
  ON WAREHOUSE PET_INSURANCE_WH
  TO ROLE PET_INSURANCE_CICD_ROLE;

GRANT USAGE
  ON DATABASE PET_INSURANCE_ANALYTICS
  TO ROLE PET_INSURANCE_CICD_ROLE;

GRANT CREATE SCHEMA
  ON DATABASE PET_INSURANCE_ANALYTICS
  TO ROLE PET_INSURANCE_CICD_ROLE;

-- PET_INSURANCE_GITHUB already exists and its OIDC workload identity is verified.
GRANT ROLE PET_INSURANCE_CICD_ROLE
  TO USER PET_INSURANCE_GITHUB;

ALTER USER PET_INSURANCE_GITHUB
  SET DEFAULT_ROLE = PET_INSURANCE_CICD_ROLE;

SHOW ROLES LIKE 'PET_INSURANCE_CICD_ROLE';
SHOW GRANTS TO USER PET_INSURANCE_GITHUB;
