USE ROLE PET_INSURANCE_CICD_ROLE;
USE WAREHOUSE PET_INSURANCE_WH;
USE DATABASE PET_INSURANCE_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS MARTS;
CREATE SCHEMA IF NOT EXISTS CONTROL;

CREATE TABLE IF NOT EXISTS RAW.SOURCE_RECORDS (
  RAW_RECORD_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  SOURCE_TABLE VARCHAR NOT NULL,
  SOURCE_PK VARCHAR NOT NULL,
  SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
  OPERATION VARCHAR NOT NULL,
  PAYLOAD VARIANT NOT NULL,
  PAYLOAD_HASH VARCHAR(64) NOT NULL,
  BATCH_ID VARCHAR NOT NULL,
  INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_RAW_SOURCE_RECORDS PRIMARY KEY (RAW_RECORD_ID)
);

CREATE TABLE IF NOT EXISTS CONTROL.INGESTION_WATERMARKS (
  SOURCE_TABLE VARCHAR PRIMARY KEY,
  LAST_UPDATED_AT TIMESTAMP_TZ,
  LAST_SOURCE_PK VARCHAR,
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CONTROL.INGESTION_BATCHES (
  BATCH_ID VARCHAR PRIMARY KEY,
  STARTED_AT TIMESTAMP_TZ NOT NULL,
  COMPLETED_AT TIMESTAMP_TZ,
  STATUS VARCHAR NOT NULL,
  ROWS_EXTRACTED NUMBER NOT NULL DEFAULT 0,
  ROWS_INSERTED NUMBER NOT NULL DEFAULT 0,
  NOTES VARCHAR
);

SELECT CURRENT_ACCOUNT() AS account_locator,
       CURRENT_REGION() AS region,
       CURRENT_ROLE() AS role,
       CURRENT_WAREHOUSE() AS warehouse,
       CURRENT_DATABASE() AS database;
