USE ROLE SNOWFLAKE_LEARNING_ROLE;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA IF NOT EXISTS PET_INSURANCE_RAW;
CREATE SCHEMA IF NOT EXISTS PET_INSURANCE_STAGING;
CREATE SCHEMA IF NOT EXISTS PET_INSURANCE_INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS PET_INSURANCE_MARTS;
CREATE SCHEMA IF NOT EXISTS PET_INSURANCE_CONTROL;

CREATE TABLE IF NOT EXISTS PET_INSURANCE_RAW.SOURCE_RECORDS (
  RAW_RECORD_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  SOURCE_TABLE VARCHAR NOT NULL,
  SOURCE_PK VARCHAR NOT NULL,
  SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
  OPERATION VARCHAR NOT NULL,
  PAYLOAD VARIANT NOT NULL,
  PAYLOAD_HASH VARCHAR(64) NOT NULL,
  BATCH_ID VARCHAR NOT NULL,
  INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_RAW_SOURCE_RECORDS PRIMARY KEY (RAW_RECORD_ID)
);

CREATE TABLE IF NOT EXISTS PET_INSURANCE_CONTROL.INGESTION_WATERMARKS (
  SOURCE_TABLE VARCHAR PRIMARY KEY,
  LAST_UPDATED_AT TIMESTAMP_TZ,
  LAST_SOURCE_PK VARCHAR,
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PET_INSURANCE_CONTROL.INGESTION_BATCHES (
  BATCH_ID VARCHAR PRIMARY KEY,
  STARTED_AT TIMESTAMP_TZ NOT NULL,
  COMPLETED_AT TIMESTAMP_TZ,
  STATUS VARCHAR NOT NULL,
  ROWS_EXTRACTED NUMBER NOT NULL DEFAULT 0,
  ROWS_INSERTED NUMBER NOT NULL DEFAULT 0,
  NOTES VARCHAR
);

SHOW SCHEMAS LIKE 'PET_INSURANCE_%' IN DATABASE SNOWFLAKE_LEARNING_DB;

SELECT CURRENT_ACCOUNT() AS account_locator,
       CURRENT_REGION() AS region,
       CURRENT_ROLE() AS role,
       CURRENT_WAREHOUSE() AS warehouse,
       CURRENT_DATABASE() AS database;
