USE ROLE SNOWFLAKE_LEARNING_ROLE;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA IF NOT EXISTS PET_INSURANCE_RAW;
CREATE SCHEMA IF NOT EXISTS PET_INSURANCE_STAGING;
CREATE SCHEMA IF NOT EXISTS PET_INSURANCE_INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS PET_INSURANCE_MARTS;
CREATE SCHEMA IF NOT EXISTS PET_INSURANCE_CONTROL;

CREATE TABLE IF NOT EXISTS PET_INSURANCE_RAW.SOURCE_RECORDS (
  RAW_RECORD_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  SOURCE_TABLE VARCHAR NOT NULL,
  SOURCE_PK VARCHAR NOT NULL,
  SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
  OPERATION VARCHAR NOT NULL,
  PAYLOAD_JSON VARCHAR,
  PAYLOAD_HASH VARCHAR(64) NOT NULL,
  BATCH_ID VARCHAR NOT NULL,
  INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_RAW_SOURCE_RECORDS PRIMARY KEY (RAW_RECORD_ID)
);

CREATE TABLE IF NOT EXISTS PET_INSURANCE_CONTROL.INGESTION_WATERMARKS (
  SOURCE_TABLE VARCHAR PRIMARY KEY,
  LAST_UPDATED_AT TIMESTAMP_TZ,
  LAST_SOURCE_PK VARCHAR,
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PET_INSURANCE_CONTROL.INGESTION_BATCHES (
  BATCH_ID VARCHAR PRIMARY KEY,
  SOURCE_TABLE VARCHAR,
  STARTED_AT TIMESTAMP_TZ NOT NULL,
  COMPLETED_AT TIMESTAMP_TZ,
  STATUS VARCHAR NOT NULL,
  SOURCE_ROWS NUMBER,
  ROWS_EXTRACTED NUMBER NOT NULL DEFAULT 0,
  ROWS_INSERTED NUMBER NOT NULL DEFAULT 0,
  WATERMARK_BEFORE_AT TIMESTAMP_TZ,
  WATERMARK_BEFORE_PK VARCHAR,
  WATERMARK_AFTER_AT TIMESTAMP_TZ,
  WATERMARK_AFTER_PK VARCHAR,
  DURATION_MS NUMBER,
  RETRY_COUNT NUMBER NOT NULL DEFAULT 0,
  RECONCILIATION_STATUS VARCHAR,
  ERROR_CLASS VARCHAR,
  ERROR_MESSAGE VARCHAR,
  GITHUB_RUN_ID VARCHAR,
  NOTES VARCHAR
);

ALTER TABLE PET_INSURANCE_CONTROL.INGESTION_BATCHES ADD COLUMN IF NOT EXISTS SOURCE_TABLE VARCHAR;
ALTER TABLE PET_INSURANCE_CONTROL.INGESTION_BATCHES ADD COLUMN IF NOT EXISTS SOURCE_ROWS NUMBER;
ALTER TABLE PET_INSURANCE_CONTROL.INGESTION_BATCHES ADD COLUMN IF NOT EXISTS WATERMARK_BEFORE_AT TIMESTAMP_TZ;
ALTER TABLE PET_INSURANCE_CONTROL.INGESTION_BATCHES ADD COLUMN IF NOT EXISTS WATERMARK_BEFORE_PK VARCHAR;
ALTER TABLE PET_INSURANCE_CONTROL.INGESTION_BATCHES ADD COLUMN IF NOT EXISTS WATERMARK_AFTER_AT TIMESTAMP_TZ;
ALTER TABLE PET_INSURANCE_CONTROL.INGESTION_BATCHES ADD COLUMN IF NOT EXISTS WATERMARK_AFTER_PK VARCHAR;
ALTER TABLE PET_INSURANCE_CONTROL.INGESTION_BATCHES ADD COLUMN IF NOT EXISTS DURATION_MS NUMBER;
ALTER TABLE PET_INSURANCE_CONTROL.INGESTION_BATCHES ADD COLUMN IF NOT EXISTS RETRY_COUNT NUMBER DEFAULT 0;
ALTER TABLE PET_INSURANCE_CONTROL.INGESTION_BATCHES ADD COLUMN IF NOT EXISTS RECONCILIATION_STATUS VARCHAR;
ALTER TABLE PET_INSURANCE_CONTROL.INGESTION_BATCHES ADD COLUMN IF NOT EXISTS ERROR_CLASS VARCHAR;
ALTER TABLE PET_INSURANCE_CONTROL.INGESTION_BATCHES ADD COLUMN IF NOT EXISTS ERROR_MESSAGE VARCHAR;
ALTER TABLE PET_INSURANCE_CONTROL.INGESTION_BATCHES ADD COLUMN IF NOT EXISTS GITHUB_RUN_ID VARCHAR;

CREATE TABLE IF NOT EXISTS PET_INSURANCE_CONTROL.INGESTION_STAGE (
  BATCH_ID VARCHAR NOT NULL,
  SOURCE_TABLE VARCHAR NOT NULL,
  SOURCE_PK VARCHAR NOT NULL,
  SOURCE_UPDATED_AT TIMESTAMP_TZ NOT NULL,
  OPERATION VARCHAR NOT NULL,
  PAYLOAD VARIANT NOT NULL,
  PAYLOAD_HASH VARCHAR(64) NOT NULL,
  STAGED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE PET_INSURANCE_CONTROL.INGESTION_STAGE ADD COLUMN IF NOT EXISTS PAYLOAD_JSON VARCHAR;

CREATE OR REPLACE VIEW PET_INSURANCE_CONTROL.INGESTION_HEALTH AS
WITH source_tables AS (
  SELECT SOURCE_TABLE
  FROM PET_INSURANCE_CONTROL.INGESTION_WATERMARKS
  UNION
  SELECT DISTINCT SOURCE_TABLE
  FROM PET_INSURANCE_CONTROL.INGESTION_BATCHES
  WHERE SOURCE_TABLE IS NOT NULL
),
latest_any AS (
  SELECT *
  FROM PET_INSURANCE_CONTROL.INGESTION_BATCHES
  WHERE SOURCE_TABLE IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY SOURCE_TABLE
    ORDER BY STARTED_AT DESC, BATCH_ID DESC
  ) = 1
),
latest_success AS (
  SELECT *
  FROM PET_INSURANCE_CONTROL.INGESTION_BATCHES
  WHERE STATUS = 'SUCCESS'
    AND SOURCE_TABLE IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY SOURCE_TABLE
    ORDER BY COMPLETED_AT DESC, BATCH_ID DESC
  ) = 1
),
latest_failure AS (
  SELECT *
  FROM PET_INSURANCE_CONTROL.INGESTION_BATCHES
  WHERE STATUS = 'FAILED'
    AND SOURCE_TABLE IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY SOURCE_TABLE
    ORDER BY COMPLETED_AT DESC, BATCH_ID DESC
  ) = 1
)
SELECT
  tables.SOURCE_TABLE,
  any_batch.STATUS AS LATEST_STATUS,
  any_batch.STARTED_AT AS LATEST_BATCH_STARTED_AT,
  success.COMPLETED_AT AS LAST_SUCCESS_AT,
  failure.COMPLETED_AT AS LAST_FAILURE_AT,
  watermark.LAST_UPDATED_AT AS SOURCE_WATERMARK_AT,
  watermark.LAST_SOURCE_PK AS SOURCE_WATERMARK_PK,
  IFF(
    watermark.LAST_UPDATED_AT IS NULL,
    NULL,
    DATEDIFF('second', watermark.LAST_UPDATED_AT, CURRENT_TIMESTAMP())
  ) AS WATERMARK_AGE_SECONDS,
  success.SOURCE_ROWS AS LAST_SOURCE_ROWS,
  success.ROWS_EXTRACTED AS LAST_ROWS_EXTRACTED,
  success.ROWS_INSERTED AS LAST_ROWS_INSERTED,
  success.DURATION_MS AS LAST_DURATION_MS,
  success.RETRY_COUNT AS LAST_RETRY_COUNT,
  success.RECONCILIATION_STATUS AS LAST_RECONCILIATION_STATUS,
  failure.ERROR_CLASS AS LAST_ERROR_CLASS,
  failure.ERROR_MESSAGE AS LAST_ERROR_MESSAGE
FROM source_tables tables
LEFT JOIN latest_any any_batch USING (SOURCE_TABLE)
LEFT JOIN latest_success success USING (SOURCE_TABLE)
LEFT JOIN latest_failure failure USING (SOURCE_TABLE)
LEFT JOIN PET_INSURANCE_CONTROL.INGESTION_WATERMARKS watermark USING (SOURCE_TABLE);

SHOW SCHEMAS LIKE 'PET_INSURANCE_%' IN DATABASE SNOWFLAKE_LEARNING_DB;

SELECT CURRENT_ACCOUNT() AS account_locator,
       CURRENT_REGION() AS region,
       CURRENT_ROLE() AS role,
       CURRENT_WAREHOUSE() AS warehouse,
       CURRENT_DATABASE() AS database;
