USE ROLE SNOWFLAKE_LEARNING_ROLE;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;

SHOW WAREHOUSES LIKE 'SNOWFLAKE_LEARNING_WH';

SELECT
    SOURCE_TABLE,
    COUNT(*) AS RAW_VERSIONS,
    COUNT(DISTINCT SOURCE_PK) AS DISTINCT_SOURCE_KEYS
FROM PET_INSURANCE_RAW.SOURCE_RECORDS
GROUP BY SOURCE_TABLE
ORDER BY SOURCE_TABLE;

SELECT
    COUNT(*) AS CLAIM_EVENT_ROWS,
    MAX(RAW_RECORD_ID) AS MAX_MODELED_RAW_RECORD_ID
FROM PET_INSURANCE_INTERMEDIATE.INT_CLAIM_EVENTS;

SELECT
    COUNT(*) AS PENDING_CLAIM_EVENT_ROWS
FROM PET_INSURANCE_RAW.SOURCE_RECORDS
WHERE LOWER(SOURCE_TABLE) = 'claims'
  AND RAW_RECORD_ID > (
      SELECT COALESCE(MAX(RAW_RECORD_ID), 0)
      FROM PET_INSURANCE_INTERMEDIATE.INT_CLAIM_EVENTS
  );

EXPLAIN USING TEXT
SELECT
    RAW_RECORD_ID,
    SOURCE_PK,
    SOURCE_UPDATED_AT,
    OPERATION,
    PAYLOAD,
    BATCH_ID,
    INGESTED_AT
FROM PET_INSURANCE_RAW.SOURCE_RECORDS
WHERE LOWER(SOURCE_TABLE) = 'claims'
  AND RAW_RECORD_ID > (
      SELECT COALESCE(MAX(RAW_RECORD_ID), 0)
      FROM PET_INSURANCE_INTERMEDIATE.INT_CLAIM_EVENTS
  );
