USE ROLE SNOWFLAKE_LEARNING_ROLE;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;

SELECT 1 / IFF(COUNT(*) = 5, 1, 0) AS PROJECT_SCHEMA_ASSERTION
FROM INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME IN (
  'PET_INSURANCE_RAW',
  'PET_INSURANCE_STAGING',
  'PET_INSURANCE_INTERMEDIATE',
  'PET_INSURANCE_MARTS',
  'PET_INSURANCE_CONTROL'
);

SELECT 1 / IFF(COUNT(*) = 3, 1, 0) AS CONTROL_RAW_TABLE_ASSERTION
FROM INFORMATION_SCHEMA.TABLES
WHERE (TABLE_SCHEMA = 'PET_INSURANCE_RAW' AND TABLE_NAME = 'SOURCE_RECORDS')
   OR (TABLE_SCHEMA = 'PET_INSURANCE_CONTROL' AND TABLE_NAME IN ('INGESTION_WATERMARKS','INGESTION_BATCHES'));

SELECT CURRENT_ACCOUNT() AS ACCOUNT_LOCATOR,
       CURRENT_REGION() AS REGION,
       CURRENT_ROLE() AS ROLE,
       CURRENT_WAREHOUSE() AS WAREHOUSE,
       CURRENT_DATABASE() AS DATABASE;
