USE ROLE SNOWFLAKE_LEARNING_ROLE;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;

-- Fail the workflow if replay produced duplicates or lost history.
SELECT 1 / IFF(
    COUNT(*) = 2
    AND COUNT(DISTINCT PAYLOAD_HASH) = 2
    AND COUNT_IF(PAYLOAD:claim_status::VARCHAR = 'SUBMITTED') = 1
    AND COUNT_IF(PAYLOAD:claim_status::VARCHAR = 'APPROVED') = 1,
    1,
    0
) AS HISTORY_ASSERTION
FROM PET_INSURANCE_RAW.SOURCE_RECORDS
WHERE SOURCE_TABLE = 'claims'
  AND SOURCE_PK = 'CLM-10042';

WITH ranked AS (
    SELECT
        SOURCE_PK,
        SOURCE_UPDATED_AT,
        PAYLOAD:claim_amount::NUMBER AS CLAIM_AMOUNT,
        PAYLOAD:approved_amount::NUMBER AS APPROVED_AMOUNT,
        PAYLOAD:claim_status::VARCHAR AS CLAIM_STATUS,
        ROW_NUMBER() OVER (
            PARTITION BY SOURCE_TABLE, SOURCE_PK
            ORDER BY SOURCE_UPDATED_AT DESC, RAW_RECORD_ID DESC
        ) AS rn
    FROM PET_INSURANCE_RAW.SOURCE_RECORDS
    WHERE SOURCE_TABLE = 'claims'
      AND SOURCE_PK = 'CLM-10042'
)
SELECT 1 / IFF(
    COUNT(*) = 1
    AND MAX(CLAIM_AMOUNT) = 11200
    AND MAX(APPROVED_AMOUNT) = 9700
    AND MAX(CLAIM_STATUS) = 'APPROVED',
    1,
    0
) AS CURRENT_STATE_ASSERTION
FROM ranked
WHERE rn = 1;

SELECT
    SOURCE_PK,
    SOURCE_UPDATED_AT,
    PAYLOAD:claim_amount::NUMBER AS CLAIM_AMOUNT,
    PAYLOAD:approved_amount::NUMBER AS APPROVED_AMOUNT,
    PAYLOAD:claim_status::VARCHAR AS CLAIM_STATUS,
    BATCH_ID
FROM PET_INSURANCE_RAW.SOURCE_RECORDS
WHERE SOURCE_TABLE = 'claims'
  AND SOURCE_PK = 'CLM-10042'
ORDER BY SOURCE_UPDATED_AT;

SELECT
    SOURCE_TABLE,
    LAST_UPDATED_AT,
    LAST_SOURCE_PK
FROM PET_INSURANCE_CONTROL.INGESTION_WATERMARKS
WHERE SOURCE_TABLE = 'claims';
